version: 2.1
orbs:
  node: circleci/node@5.2
jobs:
  test-v8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Start and Verify
          command: ./ci_script.sh
  test-v10:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "10.24"
      - run:
          name: Start and Verify
          command: ./ci_script.sh
  test-v12:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "12.22"
      - run:
          name: Start and Verify
          command: ./ci_script.sh
  test-v14:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "14.21"
      - run:
          name: Start and Verify
          command: ./ci_script.sh
  test-v16:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "16.20"
      - run:
          name: Start and Verify
          command: ./ci_script.sh
  test-v18:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "18.20"
      - run:
          name: Start and Verify
          command: ./ci_script.sh
  test-v20:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "20.18"
      - run:
          name: Start and Verify
          command: ./ci_script.sh
  test-v22:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "22.11"
      - run:
          name: Start and Verify
          command: ./ci_script.sh
workflows:
  build_and_test:
    jobs:
      - test-v16
      - test-v18
      - test-v20
      - test-v22