name: Node.js CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run:  npm install

    - name: Verify and Start
      run: |
        npm start > start.log 2>&1 &
        START_PID=$!
        sleep 5
        if grep -q "config.json file does not exist. Read the installation/setup instructions." start.log; then
          echo "Build and start completed successfully!"
          kill $START_PID
          exit 0
        else
          echo "An unexpected error occurred!"
        fi
        kill $START_PID
        exit 1